public/app/background_bookmark.js, public/manifest.json
사용자 현재 북마크 트리 전체를 받아와서 json 형식으로 변환 완료
=> add bookmark function

scripts/build.js
=> bhw commit

src/FlowerAPI.js
=> hotfix api

src/FlowerAPI.js
=> api 데이터만 리턴하도록 변경

public/app/background_login.js
=> ID토큰에서 유저 고유 아이디 추출 및 저장

src/App.css, src/App.js, src/BMButton.js, src/FlowerAPI.js, src/GraphGen.js, src/LoginButton.js, src/TestButton.js
- 부트스태랩 추가
- 기본 레이아웃 구성 
- 테스트용 버튼 임시 형성
- 임시 그래프 생성 추가
=> 부트스트랩으로 그리드 시스템 사용 및 기본 레이아웃 생성

src/BMButton.js
=> BMButton 재귀호출로 에러 발생

src/LoginButton.js
Button 태그의 href 는 작동 하지 않으므로 a 태그로 감쌌음
@subinium 리뷰부탁
=> 로그인 버튼 클릭 안되는 버그 수정

src/BMButton.js, src/FlowerAPI.js, src/GraphGen.js, src/TestButton.js
issue #35 
이번 코드는 모두 읽어보고 API 사용법 확인 부탁!
=> Flower API 리팩토링 및 사용법 변경

src/FlowerAPI.js, src/TestButton.js
=> ReadNodes , CreateNodes API 추가 및 테스트 버튼 추가

README.md
=> api 사용법 readme 에 추가

src/GraphGen.js, src/newtab.css
=> simple Treemap 구현

public/app/background.js, public/manifest.json, src/content.js, src/content_memo.js, src/css/memo.css
=> 메모 작성 기능 추가

src/FlowerAPI.js
sendRequest 에서 Project Id 와 URL 을 오버라이드 하는 작업을 제거
=> api url 버그 수정

src/bookmark.js
중간 중간 async await 오류들이 있어서 수정함
=> await 오류 수정

package.json, src/Components/BMTreemap.js, src/Components/GraphGen.js, src/Components/NavCustom.js, src/css/BMTreemap.css, yarn.lock
- 그래프 깊이별 색 변화
- icon 추가 (디펜던스install 필요)
=> icon 추가 & 그래프 깊이별 색 변화

public/manifest.json, src/Contents/content.js, src/Contents/content_sidepanel.js, src/backgrounds/background.js, src/backgrounds/background_sidepanel.js, src/css/popup.css, src/popup.js
=> popup/sidepanel 추가

src/Contents/content_memo.js, src/css/memo.css
- 삭제 및 최소화용 버튼 추가
- 디자인 변경
- 후에 memo 읽어오는 방식 수정 필요 (memo title 수정용, 현재 textarea를 찾아서 불러옴)
- css 후에 전체 bootstrap받아오도록 수정 필요 (scss 적용 또는 css module)
- 후에 markdown 까지 만들 수 있으면 좋을듯
=> memo 디자인 수정

src/Components/BMButton.js, src/Components/MainSectionGrid.js, src/Components/NavCustom.js, src/Components/SidebarCustom.js, src/css/grid.css, src/css/newtab.css, src/css/sidebar.css, src/newtab.js, src/popup.js
- sidebar custom 
- dark -> light
- newtab custom
=> newtab 전반적 디자인 수정

src/Contents/content_memo.js, src/css/memo.css
=> 메모 삭제 및 디자인 수정

src/FlowerAPI.js
=> readAllNodes API 추가

src/FlowerAPI.js
readAllNodes 익스포트 및 결과값 구조 주석 추가
=> readAllNodes 익스포트 및 결과값 구조 주석 추가

src/backgrounds/background_context_menu.js
=> url 체크후 메모 로드하도록 변경

src/FlowerAPI.js
=> getTags API 함수 정의

src/Contents/content_memo.js, src/backgrounds/background_context_menu.js
=> 메모 삭제 버그 수정

src/Contents/content_memo.js
=> 사이트 타이틀 저장

src/Components/MainSectionGrid.js, src/Components/MemoList.js, src/css/grid.css, src/css/sidebar.css
- 디자인 미완성
- 후에 Card Components에서 Toast Components로 바꿀 예정
- DB에 Memo 외의 nodes 있는 경우 에러(다음 커밋에 수정 예정)
=> 기본적인 Memo Dashboard 띄우기 구현

src/Contents/content_memo.js
=> 노드가 없을시 노드 생성하도록 변경

src/Components/BMTreemap.js, src/Components/Fileview.js, src/Components/MainSectionGrid.js, src/Components/SidebarCustom.js, src/newtab.js
- View 추가 및 디자인 개선
- Fileview + MemoList
=>  View 추가 및 디자인 개선

package.json, src/Components/MainSectionGrid.js, src/Components/MemoList.js, src/Components/NavCustom.js, src/css/memoList.css, yarn.lock
=> memo list 수정 및 알람 추가

README.md
=> readme 설치법 추가

ChromeExtension/src/Contents/content_memo.js, ChromeExtension/src/css/newtab.css, ChromeExtension/src/newtab.js, ChromeExtension/src/popup.js
- main page(newtab)
- popup(modal)
- memo
react class to function 적용 완료 
단 popup  기능에서 오류가 있으니, 수정 필요 (backend 문제인지 잘 모르겠음)
=> React Hook 적용 중

NLP/README.md, NLP/app.py, NLP/body.py, NLP/list.csv, NLP/testcode.py, NLP/utils.py
=> NLP 서버부분 레포 추가

ChromeExtension/package.json, ChromeExtension/src/Contents/content_memo.js, ChromeExtension/src/css/memo.css, ChromeExtension/yarn.lock
- 디펜던시 추가
- markdown 적용 완료
- 네이버 등 사이트에서 focusing을 빼앗기는 오류가 생기긴함
- 후에 코드를 효율적으로 변경하면 좋을 듯(기존 @bhw1994 logic을 약간 이해못함)
=> Memo에 Markdown 적용

NLP/src/receiveMessageFromSQS.py
#146 
sqs에서 python으로 메세지 받아오는 코드 구현.
추후에 완성할것
=> nlp receive message from sqs

ChromeExtension/src/Components/LoginButton.js, ChromeExtension/src/backgrounds/background_login.js
=> login url 수정

ChromeExtension/src/newtab.js
=> login button 다시 코그니토로 변경

ChromeExtension/src/Contents/content_memo.js, ChromeExtension/src/backgrounds/background_context_menu.js
=> database 형식에 로직수정

ChromeExtension/src/css/memo.scss, ChromeExtension/src/newtab.js
- Toolbar에 세부사항 추가
- 검색창, 계정 정보 등 추가
=> Toolbar 디자인 수정

ChromeExtension/src/Contents/content_memo.js, ChromeExtension/src/backgrounds/background_context_menu.js
=> edit postmemos format

ChromeExtension/src/Components/MemoList.js, ChromeExtension/src/css/memo.scss, ChromeExtension/src/css/memoList.scss, ChromeExtension/src/newtab.js
=> Memo View 변경

ChromeExtension/package.json, ChromeExtension/src/Components/LoginButton.js, ChromeExtension/src/Components/MemoList.js, ChromeExtension/src/Components/MemoModal.js, ChromeExtension/src/css/memoList.scss, ChromeExtension/src/newtab.js, ChromeExtension/yarn.lock
- Memo Dashboard 방식 변경 
- dependency 추가 (react-markdown)
=> Memo Dashboard 방식 변경

ChromeExtension/src/Components/MemoList.js, ChromeExtension/src/Components/MemoModal.js, ChromeExtension/src/newtab.js
=> memo dashboard에서 삭제

ChromeExtension/config/webpack.config.prod.js, ChromeExtension/src/Components/MemoList.js, ChromeExtension/src/Components/MemoModal.js, ChromeExtension/src/Contents/content_memo.js, ChromeExtension/src/apis/FlowerAPI.js, ChromeExtension/src/backgrounds/background_context_menu.js, ChromeExtension/src/css/memo.scss, ChromeExtension/src/css/newtab.scss, ChromeExtension/src/newtab.js
=> Error Fixed

ChromeExtension/package.json, ChromeExtension/src/Components/MemoModal.js, ChromeExtension/src/css/memoList.scss, ChromeExtension/src/css/newtab.scss, ChromeExtension/yarn.lock
- 메모 사이즈 조정 (여백등)
- 대시보드 패턴 추가
- 메모 삭제 알림 추가
- 글씨체 추가 (디펜던시 추가)
=> 개별 메모 디자인 변경

ChromeExtension/src/Components/LoginButton.js, ChromeExtension/src/Components/LogoutButton.js, ChromeExtension/src/newtab.js
- Login : 이모티콘으로 변경
- Logout : menu bar로 프로필과 함께 관리
- Search : auto sizing
=> Login/Logout/Search UI 변경

ChromeExtension/src/Components/MemoList.js, ChromeExtension/src/Components/NeedLoginPage.js, ChromeExtension/src/css/newtab.scss, ChromeExtension/src/newtab.js
- intro page 생성
- background 보다 어둡게 조정
=> intro page 생성
